### ISSUE TITLE
Unable to use this module using node require()

### ISSUE THREAD

**Issue by Pheromon** [rsocket/rsocket-js#59]
After doing "npm i rsocket-core" and creating a .js file that simply does:
> const RSC = require('rsocket-core')

I get an error similar to this one:

```
internal/modules/cjs/loader.js:302
      throw err;
      ^

Error: Cannot find module '/.../node_modules/rsocket-core/build/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:294:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:525:18)

```

Please note that I don't want to use the "import" showed in examples because I need to run a simple node script from the command line.

EDIT: This seems to work if locking version to 0.0.10 so maybe it's a problem related to the latest 0.0.11 release

**Comment by linux-china** [comment]
Same problem to me.

**Comment by robertroeser** [comment]
Hi- 

There was some issues with the 0.11 release. Please try the 0.16 release.

**Comment by linux-china** [comment]
It works with 0.16  release.  :)

**Comment by Pheromon** [comment]
It works again with versino 0.16, thanks :-)

But there is another minor issue: npm audit finds that the dependency on 'ws' for 'rsocket-websocket-server' uses an obsolete version with 1 high security vulnerability and should be upgraded.

You use ws version 2.3.1 while the latest one is 7.2.0, can you upgrade?
